### ISSUE TITLE
Add objects to tables

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/jQuery-json-editor#5]
Not yet implemented...

**Comment by IonicaBizau** [comment]
```js
hobbies: ["piano", "blogging"]
```

This should create a table like this:

|hobbies|
|---|
|piano|
|Blogging|
| text input and some add button |

**Comment by silviubogan** [comment]
@IonicaBizau, I started working on this issue, and I discovered that possible value selection with `<select>` does not work in tables. While trying to solve this issue, I reached the following question: what is the role of the following part of the if condition from [here](https://github.com/jillix/jQuery-json-editor/blob/master/src/jquery-json-editor.js#L221)?:

```
typeof Object(c.schema).type !== "string"
```

If you have any idea, please share it with me. Thanks! :smiley:

**Comment by IonicaBizau** [comment]
@silviubogan Basically, that if checks if `c` is array of non-strings or an object. In case of strings we don't need recursive calls. That's what I remember from when I wrote that code. :thought_balloon:

**Comment by silviubogan** [comment]
@IonicaBizau, why in the case of non-string arrays we need recursive calls but in the case of string arrays we don't need them? :smiley:

**Comment by IonicaBizau** [comment]
Actually, I was wrong–that means: if `c` is array and the type is explicitly mentioned (this happens when we have arrays of numbers, strings, etc. but not of objects).

**Comment by silviubogan** [comment]
@IonicaBizau, do you have any idea why, if the type of the array is explicitly specified, the recursive call should not be done?

**Comment by IonicaBizau** [comment]
Because we only need to have a recursive call in case of objects (raw or in an array).

**Comment by silviubogan** [comment]
@IonicaBizau, is there any reason why [here](https://github.com/jillix/jQuery-json-editor/blob/master/src/jquery-json-editor.js#L387) we pass the `field.schema` in that way and we do not do something like this?:

`(1)`
```js
$tr.append($("<td>").append(self.createGroup($.extend(true, field.schema, {
    type: getTypeOf(cFieldData),
    path: field.path + "." + i
}))));
```

What do you think about this method? If we have an array schema like this:

```js
hobbies: { label: "Hobbies",
    schema: {
        possible: [
            "piano",
            "blogging",
            "computers",
            "science",
            "music"
        ]
    }
}
```

the current method will not create a `<select>`, it will create a text input, because the `possible` array is not passed directly to the `createGroup` function in its object argument. Another solution would be to do this:

`(2)`
```js
$tr.append($("<td>").append(self.createGroup({
    type: getTypeOf(cFieldData),
    path: field.path + "." + i,
    schema: field.schema,
    possible: field.schema.possible
})));
```

but passing `field.schema.possible` in the schema and directly in the object too seems wrong to me. So what method do you suggest, (1) or (2), or something else?

**Comment by silviubogan** [comment]
@IonicaBizau, if you agree on the use of `$.extend` like in the example above, is it OK to use it [here](https://github.com/jillix/jQuery-json-editor/blob/master/src/jquery-json-editor.js#L394) too?

**Comment by IonicaBizau** [comment]
@silviubogan Yeah, I see. It's just a matter of implementation. I like more using `extend` (first solution), but really, feel free to hack it in any way. 

> if you agree on the use of $.extend like in the example above, is it OK to use it here too?

Yes, looks good! :balloon:

**Comment by silviubogan** [comment]
@IonicaBizau, a funny thing happens to me on [this branch](https://github.com/jillix/jQuery-json-editor/tree/add_objects_to_tables). If I normally run the example with the given data and schema, the `Age` field appears the first, and this is the normal expected behavior. If in the example I remove from the data the `age: 19` part in the schema and I explicitly tell the `number` type of the `age` field, [this `for ... in` loop](https://github.com/jillix/jQuery-json-editor/blob/add_objects_to_tables/src/jquery-json-editor.js#L597) reaches the `Age` field the last, so in the generated user interface the `Age` field is the last. Does this happen to you too? My user agent string is `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36`. I read the question and the answers on [this page](http://stackoverflow.com/q/280713/258462) but the only solution I see is to specify in the schema an array with the fields stored in a specified order. If this happens to you to, what is your opinion about this solution? :smiley:

**Comment by IonicaBizau** [comment]
> the only solution I see is to specify in the schema an array with the fields stored in a specified order.

Of course, that should be the solution. Object fields have no order. :smile_cat:

**Comment by silviubogan** [comment]
For reference, while solving this issue I discovered [this](https://code.google.com/p/chromium/issues/detail?id=539322) Chromium bug. :bug:  :smiley:

**Comment by IonicaBizau** [comment]
Little bugs everywhere! :beetle:
